version: '3.8'
services:
  app:
    image: ${DOCKER_REGISTRY:-ghcr.io}/${GITHUB_REPOSITORY:-user/yii2-app}:latest
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    environment:
      - YII_ENV=prod
    networks:
      - app-network
networks:
  app-network:
    driver: overlay