---
  - name: Deploy Yii2 application on EC2
    hosts: ec2
    become: yes
    vars:
      app_dir: /opt/yii2-app
      repo_url: "https://github.com/jitenderlunavath/yii2-docker-ci-cd-ansible.git"
      venv_dir: /opt/ansible-venv

    tasks:
      - name: Update apt package index
        ansible.builtin.apt:
          update_cache: yes
        retries: 3
        delay: 5

      - name: Install required packages
        ansible.builtin.apt:
          name:
            - git
            - curl
            - unzip
            - python3-pip
            - python3-apt
            - python3-docker
            - python3-venv
            - php-curl
            - php-mysql
            - php-xml
            - php-mbstring
            - mysql-client
          state: present

      - name: Install Docker
        ansible.builtin.apt:
          name:
            - docker.io
            - docker-compose
          state: present

      - name: Start and enable Docker service
        ansible.builtin.systemd:
          name: docker
          state: started
          enabled: yes

      - name: Add ubuntu user to docker group
        ansible.builtin.user:
          name: ubuntu
          groups: docker
          append: yes

      - name: Create Python virtual environment
        ansible.builtin.command:
          cmd: python3 -m venv {{ venv_dir }}
          creates: "{{ venv_dir }}/bin/activate"

      - name: Install jsondiff in virtual environment
        ansible.builtin.pip:
          name: jsondiff
          state: present
          virtualenv: "{{ venv_dir }}"
          virtualenv_python: python3

      - name: Install Composer
        ansible.builtin.shell: |
          curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
        args:
          creates: /usr/local/bin/composer

      - name: Clone the repository
        ansible.builtin.git:
          repo: "{{ repo_url }}"
          dest: "{{ app_dir }}"
          version: main
          force: yes
        register: git_clone

      - name: Set permissions for app directory
        ansible.builtin.file:
          path: "{{ app_dir }}"
          owner: root
          group: root
          mode: '0755'
          recurse: yes

      - name: Run composer install in app directory
        ansible.builtin.command:
          cmd: composer install --no-dev --optimize-autoloader --ignore-platform-reqs
          chdir: "{{ app_dir }}"
        environment:
          COMPOSER_HOME: /root/.composer
        when: git_clone.changed

      - name: Remove existing Docker stack
        community.docker.docker_stack:
          state: absent
          name: yii2
        ignore_errors: yes

      - name: Deploy Yii2 app with Docker stack
        community.docker.docker_stack:
          state: present
          name: yii2
          compose: "{{ app_dir }}/docker-compose.yml"
        environment:
          PYTHONPATH: "{{ venv_dir }}/lib/python3.10/site-packages"
        vars:
          ansible_python_interpreter: "{{ venv_dir }}/bin/python3"
